version: '3'

services:
  frontend:
    build:
      context: ../AngularFrontend-InsomeaInternship-2024
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"


